# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: assignment_paperclip/development   # name this whatever you want
  host: localhost
  pool: 5                             # Not required
  timeout: 5000                       # Not required

test:
  adapter: postgresql
  database: assignment_paperclip/test   # name this whatever you want
  host: localhost
  pool: 5                             # Not required
  timeout: 5000                       # Not required

production:
  adapter: postgresql
  database: assignment_paperclip/production   # name this whatever you want
  host: localhost
  pool: 5                             # Not required
  timeout: 5000