# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: assignment_photos_emails_delays_development

test:
  <<: *default
  host: localhost
  database: assignment_photos_emails_delays_test

production:
  <<: *default
  database: assignment_photos_emails_delays_production
